#!/bin/sh
# Start/stop the feeds_ifce storage daemon.

### BEGIN INIT INFO
# Provides:          feeds_ifce
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      $network
# Should-Stop:       $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Citizen Desk feeds daemon
# Description:       the Citizen Desk feeds interface daemon
### END INIT INFO

. /lib/lsb/init-functions

DAEMON=/opt/citizendesk/lib/citizendesk/feeds/start.py
PIDFILE=/opt/citizendesk/var/run/feeds_ifce.pid
LOGFILE=/opt/citizendesk/var/log/citizendesk/feeds_ifce.log
WEBPORT=9060
WEBHOST=localhost
MONGOHOST=localhost
MONGOPORT=27017
DBNAME=citizendesk
NEWSTWISTER_URL="http://localhost:9054/"
SMSCONF=/opt/citizendesk/etc/citizendesk/sms_ifce.yaml
CLIENTS=/opt/citizendesk/etc/citizendesk/feed_allowed.conf
USER=citizendesk
GROUP=citizendesk

# check/touch/chown the log file

test -x $DAEMON || exit 0

case "$1" in
  start)
    # move/roll log files, if they are too big
    touch $LOGFILE
    chown $USER.$GROUP $LOGFILE
    touch $PIDFILE
    chown $USER.$GROUP $PIDFILE

    log_daemon_msg "Starting Citizen Desk feeds daemon"
    log_progress_msg "feeds_ifce"

    start-stop-daemon --start --quiet --pidfile $PIDFILE --startas $DAEMON -- \
        -w $WEBHOST -p $WEBPORT -i $PIDFILE -l $LOGFILE \
        -m $MONGOHOST -o $MONGOPORT -b $DBNAME -n $NEWSTWISTER_URL \
        -d -u $USER -g $GROUP -a $CLIENTS -s $SMSCONF || true

    log_end_msg 0
    ;;

  stop)
    log_daemon_msg "Stopping Citizen Desk feeds daemon"
    log_progress_msg "feeds_ifce"
    start-stop-daemon --stop --quiet \
        --pidfile $PIDFILE || true
    log_end_msg 0
    ;;

  reload)
    # We don't have support for this yet.
    exit 1
    ;;

  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|force-reload}"
    exit 1

esac

exit 0
