#!/bin/sh
# Start/stop the twt_ingest storage daemon.

### BEGIN INIT INFO
# Provides:          twt_ingest
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      $network
# Should-Stop:       $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Twt-ingest daemon
# Description:       the Twt-ingest controller daemon
### END INIT INFO

. /lib/lsb/init-functions

DAEMON=/opt/citizendesk/lib/citizendesk/ingest/twt/start.py
PIDFILE=/opt/citizendesk/var/run/twt_ingestd.pid
LOGFILE=/opt/citizendesk/var/log/citizendesk/twt_ingest.log
WEBPORT=9055
WEBHOST=localhost
MONGOHOST=localhost
MONGOPORT=27017
DBNAME=citizendesk
CLIENTS=/opt/citizendesk/etc/citizendesk/twt_allowed.conf
USER=citizendesk
GROUP=citizendesk

# check/touch/chown the log file

test -x $DAEMON || exit 0

case "$1" in
  start)
    # move/roll log files, if they are too big
    touch $LOGFILE
    chown $USER.$GROUP $LOGFILE
    touch $PIDFILE
    chown $USER.$GROUP $PIDFILE

    log_daemon_msg "Starting Twt-ingest daemon"
    log_progress_msg "twt_ingest"

    start-stop-daemon --start --quiet --pidfile $PIDFILE --startas $DAEMON -- \
        -w $WEBHOST -p $WEBPORT -i $PIDFILE -l $LOGFILE \
        -m $MONGOHOST -o $MONGOPORT -b $DBNAME \
        -d -u $USER -g $GROUP -a $CLIENTS || true

    log_end_msg 0
    ;;

  stop)
    log_daemon_msg "Stopping Twt-ingest daemon"
    log_progress_msg "twt_ingest"
    start-stop-daemon --stop --quiet \
        --pidfile $PIDFILE || true
    log_end_msg 0
    ;;

  reload)
    # We don't have support for this yet.
    exit 1
    ;;

  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|force-reload}"
    exit 1

esac

exit 0
